### ISSUE TITLE
[0.17.X] Space exploration FARL error? Maybe bounded?

### ISSUE THREAD

**Issue by IIPoliII** [Choumiko/FARL#106]
Hello, i am having this issue when i try to place some rails and i can't use farl for some reason
![image](https://user-images.githubusercontent.com/29628512/57987951-8b235400-7a88-11e9-812b-fe9bc6e7e066.png)
Any ideas on this issue?

**Comment by Choumiko** [comment]
Can you upload the save somewhere?
I can reproduce a similar error by placing ghost rails in front of FARL, clicking on Start and then removing the ghost rails before clicking Yes or No.

**Comment by IIPoliII** [comment]
I think it was the blueprint way, since if i ever place a ghost and say yes my bots works on it too and they break everything.

**Comment by IIPoliII** [comment]
But i don't understand how you place 2 rails now one for each way ^^'

**Comment by Choumiko** [comment]
it should be fixed in the latest update

For multiple rails, this post: https://forums.factorio.com/viewtopic.php?f=61&t=9411#p75176 is still correct for the most part. After creating the 2 blueprints you just have to go to the settings (Gear icon) and click the "Read" button with the blueprint on the cursor (once for diagonal blueprint, once for the straight bp)
