### ISSUE TITLE
Decide on a proper name for -root mode

### ISSUE THREAD

**Issue by Choumiko** [Choumiko/FARL#12]
Car mode, Car+ mode, Car mode+
Exploration mode ? What's it going to be.

**Comment by jocker-il** [comment]
I don't know why ask me, I don't like the name "car mode"- I'm more for "exploration mode" or "tour mode" (can you add a tool-tip when hovering over buttons - an explanation would be good, especially the part about needing two loco's),

But, if I have to choose one, It's "car+ mode" because we'r enhancing the car, not the mode...

**Comment by Choumiko** [comment]
Not asking you directly, that's more like a reminder for me, but input is always welcome. You are right about car+ vs mode+. I'll post on the forums for other users to share their thoughts.
Tooltips weren't possible the last time i tried.

**Comment by jocker-il** [comment]
Oh, I misunderstood... the e-mail I got was formatted so that I thought you directed a question to me.

anyway, glad my suggestions help

**Comment by Choumiko** [comment]
-root mode no longer exists, problem solved ;)
